insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',120366453 , 'Manutenção Anual');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',676890257 , 'Taxa de adesão');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991765, 'Multa');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991766, 'Manutenção Anual');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991767, 'Segunda via blackcard');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991768, 'Cobrança atrasada');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991770, 'Pagamento em Boleto');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991771, 'Mensalidade Black');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991772, 'Mensalidade Smart');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991773, 'Avaliação Médica');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991774, 'Mensalidade simple');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991775, 'Contestacao');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991776, 'Acerto de pendência via TEF');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991769, 'Convite Festa');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991777, 'Plano Anual');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991778, 'Ponerse al día - Datáfono');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991779, 'Pagamento de dívida através de POS');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991780, 'Pagamento de dívida através do TOTEM');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991783, 'Pagamento de divida atráves do espaço do aluno');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991784, 'Smart Fit Body');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991785, 'Mensalidade Studio');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991786, 'Manutenção Anual (Studio)');
insert into product_from_to (origin_system, front_product_id, front_product_name) value ('smartsystem',1002991787, 'Pagamento via Carteira Digital');