insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',1	,'Smart', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',2	,'Black', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',3	,'Personal 1', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',4	,'Personal 2', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',5	,'Personal 3', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',6	,'Personal Interno', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',10	,'Personal Externo', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',12	,'Simple', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',20	,'Personal Externo 2', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',25	,'Smart Drinks', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',26	,'Black Drinks', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',27	,'Personal Interno Black', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',28	,'Personal Externo Black', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',36	,'Passe Diário', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',41	,'Studio', 'plan');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',1	,'Smart Fit Energy', 'addon');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',2	,'Smart Fit Body', 'addon');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',3	,'Smart Nutri', 'addon');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',4	,'Personal Trainer', 'addon');
insert into plan_or_addon_from_to(plan_or_addon_from_to_origin_system, front_plan_or_addon_id, front_plan_or_addon_name, type) values ('smartsystem',5	,'Black Personal Trainer', 'addon');