select * from order_to_cash;
select * from invoice_customer;
select * from receivable;
select * from customer;
select * from supplier;
select * from payable;
select * from clustered_receivable;
-- select * from receivable_erp_configurations;
select * from invoice;
select * from invoice_items;
-- select * from chargeback;
-- select * from clustered_chargeback;

select * from payable;
-- select * from conciliated_payed_receivable;
-- select * from chargeback;
-- select * from refund;
-- select * from refund_items;
-- select * from organization_from_to;
-- select * from organization_from_to_version;
-- select * from product_from_to;
-- select * from product_from_to_version;