select * from order_to_cash order by created_at desc ;
select * from invoice_customer order by created_at desc ;
select * from receivable order by created_at desc ;
-- select * from customer;
-- select * from supplier;
-- select * from payable;
select * from clustered_receivable order by created_at desc ;
-- select * from receivable_erp_configurations;
select * from invoice order by created_at desc ;
select * from invoice_items order by created_at desc ;
-- select * from chargeback;
-- select * from clustered_chargeback;
-- select * from payable;
-- select * from conciliated_payed_receivable;
-- select * from chargeback;
-- select * from refund;
-- select * from refund_items;
-- select * from organization_from_to;
-- select * from organization_from_to_version;
-- select * from product_from_to;
-- select * from product_from_to_version;
-- select * from plan_from_to;
-- select * from plan_from_to_version;
-- select * from addon_from_to;
-- select * from addon_from_to_version;